INSERT INTO EMP
VALUES(1, 'BARTH Florent', 'CHEF DE PROJET', 3, 13000, 2);
INSERT INTO EMP
VALUES(2, 'XAVIER Richard', 'CHERCHEUR', 3, 21000, 1);
INSERT INTO EMP
VALUES(3, 'NICOLE Chris', 'CHERCHEUR', NULL, 25000, 1);
INSERT INTO EMP
VALUES(4, 'BLAKE John', 'DEVELOPPEUR', 6, 8000, 2);
INSERT INTO EMP
VALUES(5, 'DUPONT Jean', 'DEVELOPPEUR', 3, 9000, 2);
INSERT INTO EMP
VALUES(6, 'MARTIN Alexandre', 'COMPTABLE', 3, 10000, 3);
INSERT INTO EMP
VALUES(7, 'RAY Benjamin', 'COMPTABLE', 3, 10000, 3);
INSERT INTO EMP
VALUES(8, 'MILLER Pascal', 'DEVELOPPEUR', 3, 9000, 2);
INSERT INTO EMP
VALUES(9, 'FORD John', 'DIRECTEUR', 3, 30000, 4);

INSERT INTO DEPT
VALUES(1, 'RECHERCHE', 'DIJON');
INSERT INTO DEPT
VALUES(2, 'DEVELOPPEMENT', 'NEW-YORK');
INSERT INTO DEPT
VALUES(3, 'FACTURATION', 'PARIS');
INSERT INTO DEPT
VALUES(4, 'DIRECTION', 'LONDRES');
