#include "Bouton.h"




Bouton::Bouton()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D1A begin
{
}
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D1A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Bouton::Bouton(const Bouton &)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D1C begin
{
}
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D1C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Bouton::Bouton(bool cercle, bool etat)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D1F begin
{
}
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D1F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Bouton::definir(int , int , int , int , int , int , bool )
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D23 begin
{
}
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D23 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Bouton::definir(int , int , int , Couleur , bool )
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D39 begin
{
}
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D39 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Bouton::activer()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D5B begin
{
}
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D5B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Bouton::desactiver()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D5D begin
{
}
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D5D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Bouton::actif() const 
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D5F begin
{
    return false;
}
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D5F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Bouton::afficher(Fenetre &)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D61 begin
{
}
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D61 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Bouton::effacer(Fenetre &)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D64 begin
{
}
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D64 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
