#include "BoutonTexte.h"




BoutonTexte::BoutonTexte()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D75 begin
{
}
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D75 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

BoutonTexte::BoutonTexte(Bouton , const char *)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D77 begin
{
}
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D77 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

BoutonTexte::BoutonTexte(const BoutonTexte &)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D7C begin
{
}
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D7C end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

BoutonTexte::~BoutonTexte()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D81 begin
{
}
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D81 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void BoutonTexte::afficher() const 
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D87 begin
{
}
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D87 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void BoutonTexte::effacer() const 
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D8A begin
{
}
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D8A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void BoutonTexte::definirTexte(const char *)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-3--52-25-2ca19465:15364d9d519:-8000:0000000000000D5A begin
{
}
// section 10-3--52-25-2ca19465:15364d9d519:-8000:0000000000000D5A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
