#include "Couleur.h"




Couleur::Couleur(int , int , int )
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-0-2-15--55854bca:14497504373:-8000:0000000000000AF1 begin
{
}
// section 10-0-2-15--55854bca:14497504373:-8000:0000000000000AF1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Couleur::Couleur(const Couleur &)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-0-2-15--55854bca:14497504373:-8000:0000000000000AFC begin
{
}
// section 10-0-2-15--55854bca:14497504373:-8000:0000000000000AFC end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Couleur::changeCouleur(int , int , int )
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-0-2-15--55854bca:14497504373:-8000:0000000000000AE6 begin
{
}
// section 10-0-2-15--55854bca:14497504373:-8000:0000000000000AE6 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Couleur::rouge() const 
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-0-2-15--55854bca:14497504373:-8000:0000000000000AEB begin
{
    return 0;
}
// section 10-0-2-15--55854bca:14497504373:-8000:0000000000000AEB end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Couleur::vert() const 
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-0-2-15--55854bca:14497504373:-8000:0000000000000AED begin
{
    return 0;
}
// section 10-0-2-15--55854bca:14497504373:-8000:0000000000000AED end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Couleur::bleu() const 
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-0-2-15--55854bca:14497504373:-8000:0000000000000AEF begin
{
    return 0;
}
// section 10-0-2-15--55854bca:14497504373:-8000:0000000000000AEF end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Couleur::Couleur()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000CCC begin
{
    
}
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000CCC end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
