#include "Souris.h"




Souris::Souris()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-0-2-15--55854bca:14497504373:-8000:0000000000000B08 begin
{
}
// section 10-0-2-15--55854bca:14497504373:-8000:0000000000000B08 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Souris::Souris(const Souris &)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-0-2-15--55854bca:14497504373:-8000:0000000000000B0A begin
{
}
// section 10-0-2-15--55854bca:14497504373:-8000:0000000000000B0A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Souris::associerA(Fenetre &)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-0-2-15--55854bca:14497504373:-8000:0000000000000B0E begin
{
}
// section 10-0-2-15--55854bca:14497504373:-8000:0000000000000B0E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Souris::position(int &, int &, int &) const 
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-0-2-15--55854bca:14497504373:-8000:0000000000000B11 begin
{
}
// section 10-0-2-15--55854bca:14497504373:-8000:0000000000000B11 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Souris::testeBoutons(int &, int &, int &) const 
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-0-2-15--55854bca:14497504373:-8000:0000000000000B16 begin
{
    return false;
}
// section 10-0-2-15--55854bca:14497504373:-8000:0000000000000B16 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
