#include "Cercle.h"




void Cercle::placer(int , int )
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000CF0 begin
{
}
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000CF0 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Cercle::dimensionner(int )
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000CF4 begin
{
}
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000CF4 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Cercle::definirCouleur(int , int , int )
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000CF6 begin
{
}
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000CF6 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Cercle::definirCouleur(Couleur )
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000CFC begin
{
}
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000CFC end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Cercle::coordX() const 
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000CFF begin
{
    return 0;
}
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000CFF end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Cercle::coordY() const 
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D01 begin
{
    return 0;
}
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D01 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Cercle::rayon() const 
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D03 begin
{
    return 0;
}
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D03 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Couleur Cercle::couleur() const 
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D05 begin
{
}
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D05 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Cercle::afficher(Fenetre &) const 
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D07 begin
{
}
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D07 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Cercle::effacer(Fenetre &) const 
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D0A begin
{
}
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D0A end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool Cercle::touche(int , int ) const 
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D0D begin
{
    return false;
}
// section 10-3--52-28-79e3f0a1:14c0d7449db:-8000:0000000000000D0D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
