#include "Fenetre.h"




Fenetre::Fenetre()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-0-2-15-5daf62e1:14496d1e127:-8000:0000000000000ACF begin
{
}
// section 10-0-2-15-5daf62e1:14496d1e127:-8000:0000000000000ACF end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Fenetre::Fenetre(const char *, int , int , int , int , int , int , int )
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-0-2-15-5daf62e1:14496d1e127:-8000:0000000000000AD1 begin
{
}
// section 10-0-2-15-5daf62e1:14496d1e127:-8000:0000000000000AD1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Fenetre::Fenetre(const Fenetre &)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-0-2-15-5daf62e1:14496d1e127:-8000:0000000000000AEC begin
{
}
// section 10-0-2-15-5daf62e1:14496d1e127:-8000:0000000000000AEC end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Fenetre::apparait(const char *, int , int , int , int , int , int , int )
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-333d4989:14496bc500f:-8000:0000000000000A6E begin
{
}
// section 127-0-1-1-333d4989:14496bc500f:-8000:0000000000000A6E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Fenetre::disparait()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-333d4989:14496bc500f:-8000:0000000000000AB3 begin
{
}
// section 127-0-1-1-333d4989:14496bc500f:-8000:0000000000000AB3 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Fenetre::deplacerEn(int , int )
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-333d4989:14496bc500f:-8000:0000000000000AB5 begin
{
}
// section 127-0-1-1-333d4989:14496bc500f:-8000:0000000000000AB5 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Fenetre::hauteur() const 
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-333d4989:14496bc500f:-8000:0000000000000AB9 begin
{
    return 0;
}
// section 127-0-1-1-333d4989:14496bc500f:-8000:0000000000000AB9 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Fenetre::largeur() const 
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-333d4989:14496bc500f:-8000:0000000000000ABB begin
{
    return 0;
}
// section 127-0-1-1-333d4989:14496bc500f:-8000:0000000000000ABB end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Fenetre::coordEnX() const 
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-333d4989:14496bc500f:-8000:0000000000000ABD begin
{
    return 0;
}
// section 127-0-1-1-333d4989:14496bc500f:-8000:0000000000000ABD end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Fenetre::coordEnY() const 
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-333d4989:14496bc500f:-8000:0000000000000ABF begin
{
    return 0;
}
// section 127-0-1-1-333d4989:14496bc500f:-8000:0000000000000ABF end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Couleur Fenetre::couleurFond() const 
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-333d4989:14496bc500f:-8000:0000000000000AC1 begin
{
}
// section 127-0-1-1-333d4989:14496bc500f:-8000:0000000000000AC1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Fenetre::choixCouleurTrace(int , int , int )
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-333d4989:14496bc500f:-8000:0000000000000CE9 begin
{
}
// section 127-0-1-1-333d4989:14496bc500f:-8000:0000000000000CE9 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Fenetre::choixCouleurTrace(Couleur )
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-333d4989:14496bc500f:-8000:0000000000000CEE begin
{
}
// section 127-0-1-1-333d4989:14496bc500f:-8000:0000000000000CEE end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Fenetre::traceLigne(int , int , int , int , int )
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-333d4989:14496bc500f:-8000:0000000000000CFF begin
{
}
// section 127-0-1-1-333d4989:14496bc500f:-8000:0000000000000CFF end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Fenetre::traceArc(int , int , int , int , int , int , int )
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-333d4989:14496bc500f:-8000:0000000000000CF1 begin
{
}
// section 127-0-1-1-333d4989:14496bc500f:-8000:0000000000000CF1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Fenetre::remplitReclangle(int , int , int , int )
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-333d4989:14496bc500f:-8000:0000000000000D07 begin
{
}
// section 127-0-1-1-333d4989:14496bc500f:-8000:0000000000000D07 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Fenetre::remplitEllipse(int , int , int , int )
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-333d4989:14496bc500f:-8000:0000000000000D0D begin
{
}
// section 127-0-1-1-333d4989:14496bc500f:-8000:0000000000000D0D end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Fenetre::ecrit(int , int , const char *)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 127-0-1-1-333d4989:14496bc500f:-8000:0000000000000D13 begin
{
}
// section 127-0-1-1-333d4989:14496bc500f:-8000:0000000000000D13 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Fenetre::ecrit(int , int , int )
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-0-2-15-5daf62e1:14496d1e127:-8000:0000000000000AB5 begin
{
}
// section 10-0-2-15-5daf62e1:14496d1e127:-8000:0000000000000AB5 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Fenetre::afficheImage(const char *, int , int )
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-0-2-15-5daf62e1:14496d1e127:-8000:0000000000000ABA begin
{
}
// section 10-0-2-15-5daf62e1:14496d1e127:-8000:0000000000000ABA end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Fenetre::afficheImage(Image , int , int )
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-0-2-15-5daf62e1:14496d1e127:-8000:0000000000000AC3 begin
{
}
// section 10-0-2-15-5daf62e1:14496d1e127:-8000:0000000000000AC3 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Fenetre::effacer()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-0-2-15-5daf62e1:14496d1e127:-8000:0000000000000ACA begin
{
}
// section 10-0-2-15-5daf62e1:14496d1e127:-8000:0000000000000ACA end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void Fenetre::delai(int )
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-0-2-15-5daf62e1:14496d1e127:-8000:0000000000000ACC begin
{
}
// section 10-0-2-15-5daf62e1:14496d1e127:-8000:0000000000000ACC end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
