#include "Image.h"




Image::Image(const char *)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-0-2-15--55854bca:14497504373:-8000:0000000000000AFF begin
{
}
// section 10-0-2-15--55854bca:14497504373:-8000:0000000000000AFF end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Image::Image(const Image &)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-0-2-15--55854bca:14497504373:-8000:0000000000000B1B begin
{
}
// section 10-0-2-15--55854bca:14497504373:-8000:0000000000000B1B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Image::hauteur() const 
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-0-2-15--55854bca:14497504373:-8000:0000000000000B02 begin
{
    return 0;
}
// section 10-0-2-15--55854bca:14497504373:-8000:0000000000000B02 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Image::largeur() const 
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section 10-0-2-15--55854bca:14497504373:-8000:0000000000000B05 begin
{
    return 0;
}
// section 10-0-2-15--55854bca:14497504373:-8000:0000000000000B05 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
