INSERT INTO EQUIPE VALUES(1, 'PSG', 150000, 8500000);
INSERT INTO EQUIPE VALUES(2, 'Bordeaux', 125000, 6750000);
INSERT INTO EQUIPE VALUES(3, 'AS Monaco', 45000, 5985000);
INSERT INTO EQUIPE VALUES(4, 'Real Madrid', 56000, 4876000);

INSERT INTO JOUEUR VALUES(1, 'ABIDAL', 'Eric', 'Francais', 4, 1);
INSERT INTO JOUEUR VALUES(2, 'ANTHONY', 'Hounier', 'Francais', 7, 2);
INSERT INTO JOUEUR VALUES(3, 'BALE', 'Gareth', 'Anglais', 5, 4);
INSERT INTO JOUEUR VALUES(4, 'BENZEMA', 'Karim', 'Francais', 22, 4);
INSERT INTO JOUEUR VALUES(5, 'CABELLA', 'Remy', 'Francais', 6, 2);
INSERT INTO JOUEUR VALUES(6, 'CASILLAS', 'Iker', 'Espagnol', 8, 4);
INSERT INTO JOUEUR VALUES(7, 'DIABATE', 'Cheik', 'Francais', 14, 3);
INSERT INTO JOUEUR VALUES(8, 'GOURKUFF', 'Yoann', 'Francais', 10, 3);
INSERT INTO JOUEUR VALUES(9, 'RAMOS', 'Sergio', 'Espagnol', 7, 4);
INSERT INTO JOUEUR VALUES(10, 'TOULALAN', 'Jeremy', 'Francais', 12, 1);

INSERT INTO COMPETITION VALUES(1, 'Ligue des Champions', 'Ligue');
INSERT INTO COMPETITION VALUES(2, 'Coupe de France', 'Coupe');
INSERT INTO COMPETITION VALUES(3, 'Championnat', 'Championnat');

INSERT INTO PARTICIPER VALUES(1, 1, 1);
INSERT INTO PARTICIPER VALUES(2, 2, 2);
INSERT INTO PARTICIPER VALUES(3, 3, 3);
INSERT INTO PARTICIPER VALUES(4, 1, 4);

