
/* ====================================================================================== */
/* 				                       LISTE DES JOUEURS                                  */
/* ====================================================================================== */

/* Joueurs de l'equipe nationale du Bresil (1) */

/* Guardien */
INSERT INTO JOUEUR
VALUES(101, 12, 'GROHE', 'Marcelo', 'Bresilien', 0, 1);

/* Defenseurs */
INSERT INTO JOUEUR
VALUES(102, 14, 'SILVA', 'Thiago', 'Bresilien', 52, 1);
INSERT INTO JOUEUR
VALUES(103, 4, 'LUIS', 'David', 'Bresilien', 47, 1);
INSERT INTO JOUEUR
VALUES(104, 3, 'MIRANDA', 'Joao', 'Bresilien', 13, 1);

/* Milieux */
INSERT INTO JOUEUR
VALUES(105, 21, 'COUTINHO', 'Philippe', 'Bresilien', 5, 1);
INSERT INTO JOUEUR
VALUES(106, 18, 'FIRMINO', 'Roberto', 'Bresilien', 2, 1);
INSERT INTO JOUEUR
VALUES(107, 17, 'GUSTAVO', 'Luiz', 'Bresilien', 30, 1);
INSERT INTO JOUEUR
VALUES(108, 8, 'MENDES TRINDADE', 'Elias', 'Bresilien', 17, 1);

/* Attaquants */
INSERT INTO JOUEUR
VALUES(109, 9, 'TARDELLI', 'Diego', 'Bresilien', 9, 1);
INSERT INTO JOUEUR
VALUES(110, 7, 'COSTA', 'Douglas', 'Bresilien', 2, 1);
INSERT INTO JOUEUR
VALUES(111, 10, 'SILVA SANTOS JUNIOR', 'Neymar', 'Bresilien', 60, 1);

/* ====================================================================================== */

/* Joueurs de l'equipe nationale du Chili (2) */

/* Guardien */
INSERT INTO JOUEUR
VALUES(201, 1, 'BRAVO', 'Claudio', 'Chilien', 78, 2);

/* Defenseurs */
INSERT INTO JOUEUR
VALUES(202, 3, 'JARA', 'Gonzales', 'Chilien', 63, 2);
INSERT INTO JOUEUR
VALUES(203, 5, 'MEDEL', 'Gary', 'Chilien', 58, 2);
INSERT INTO JOUEUR
VALUES(204, 7, 'ISLA', 'Mauricio', 'Chilien', 44, 2);

/* Milieux */
INSERT INTO JOUEUR
VALUES(205, 9, 'FERNANDEZ', 'Matias', 'Chilien', 59, 2);
INSERT INTO JOUEUR
VALUES(206, 11, 'VALDIVIA', 'Jorge', 'Chilien', 55, 2);
INSERT INTO JOUEUR
VALUES(207, 13, 'CARMONA', 'Carlos', 'Chilien', 42, 2);
INSERT INTO JOUEUR
VALUES(208, 15, 'FUENZALIDA', 'Jose Pedro', 'Chilien', 21, 2);

/* Attaquants */
INSERT INTO JOUEUR
VALUES(209, 17, 'SANCHEZ', 'Alexis', 'Chilien', 64, 2);
INSERT INTO JOUEUR
VALUES(210, 19, 'BEAUSEJOUR', 'Jean', 'Chilien', 57, 2);
INSERT INTO JOUEUR
VALUES(211, 21, 'VARGAS', 'Eduardo', 'Chilien', 27, 2);

/* ====================================================================================== */

/* Joueurs de l'equipe nationale de Colombie (3) */

/* Guardien */
INSERT INTO JOUEUR
VALUES(301, 1, 'VARGAS', 'Camilo', 'Colombien', 0, 3);

/* Defenseurs */
INSERT INTO JOUEUR
VALUES(302, 3, 'ARMENO', 'Pablo', 'Colombien', 49, 3);
INSERT INTO JOUEUR
VALUES(303, 5, 'ZAPATA', 'Cristian', 'Colombien', 20, 3);
INSERT INTO JOUEUR
VALUES(304, 7, 'VALDES', 'Carlos', 'Colombien', 12, 3);

/* Milieux */
INSERT INTO JOUEUR
VALUES(305, 9, 'GUARIN', 'Fredy', 'Colombien', 47, 3);
INSERT INTO JOUEUR
VALUES(306, 11, 'AGUILAR', 'Abel', 'Colombien', 46, 3);
INSERT INTO JOUEUR
VALUES(307, 13, 'SANCHEZ', 'Carlos', 'Colombien', 43, 3);
INSERT INTO JOUEUR
VALUES(308, 15, 'TORRES', 'Macnelly', 'Colombien', 38, 3);

/* Attaquants */
INSERT INTO JOUEUR
VALUES(309, 17, 'FALCAO', 'Radamel', 'Colombien', 50, 3);
INSERT INTO JOUEUR
VALUES(310, 19, 'GUTIERREZ', 'Teofilo', 'Colombien', 27, 3);
INSERT INTO JOUEUR
VALUES(311, 21, 'MARTINEZ', 'Jackson', 'Colombien', 25, 3);

/* ====================================================================================== */

/* Joueurs de l'equipe nationale d'Uruguay (4) */

/* Guardien */
INSERT INTO JOUEUR
VALUES(401, 1, 'MUSLERA', 'Fernando', 'Uruguay', 63, 4);

/* Defenseurs */
INSERT INTO JOUEUR
VALUES(402, 3, 'GODIN',  'Diego', 'Uruguay', 83, 4);
INSERT INTO JOUEUR
VALUES(403, 5, 'CORUJO', 'Mathias', 'Uruguay', 2, 4);
INSERT INTO JOUEUR
VALUES(404, 6, 'PEREIRA', 'Alvaro', 'Uruguay', 62, 4);

/* Milieux */
INSERT INTO JOUEUR
VALUES(405, 7, 'RODRIGUEZ', 'Cristian', 'Uruguay', 79, 4);
INSERT INTO JOUEUR
VALUES(406, 14, 'LODEIRO', 'Nicolas', 'Uruguay', 31, 4);
INSERT INTO JOUEUR
VALUES(407, 17, 'AREVALO', 'Egidio', 'Uruguay', 61, 4);
INSERT INTO JOUEUR
VALUES(408, 18, 'MAYADA', 'Camilo', 'Uruguay', 2, 4);

/* Attaquants */
INSERT INTO JOUEUR
VALUES(409, 8, 'HERNANDEZ', 'Able', 'Uruguay', 16, 4);
INSERT INTO JOUEUR
VALUES(410, 9, 'ROLAN', 'Diego', 'Uruguay', 5, 4);
INSERT INTO JOUEUR
VALUES(411, 11, 'STUANI', 'Christian', 'Uruguay', 16, 4);

/* ====================================================================================== */

/* Joueurs de l'equipe nationale de France (5) */

/* Gardien */
INSERT INTO JOUEUR
VALUES(501, 1, 'LLORIS', 'Hugo', 'Francais', 72, 5);

/* Defenseurs */
INSERT INTO JOUEUR
VALUES(502, 15, 'SAGNA', 'Bacary', 'Francais', 54, 5);
INSERT INTO JOUEUR
VALUES(503, 2, 'JALLET', 'Christophe', 'Francais', 10, 5);
INSERT INTO JOUEUR
VALUES(504, 4, 'VARANE', 'Raphael', 'Francais', 27, 5);

/* Milieux */
INSERT INTO JOUEUR
VALUES(505, 12, 'DIARRA', 'Lassana', 'Francais', 31, 5);
INSERT INTO JOUEUR
VALUES(506, 22, 'SCHNEIDERLIN', 'Morgan', 'Francais', 15, 5);
INSERT INTO JOUEUR
VALUES(507, 6, 'CABAYE', 'Yohan', 'Francais', 44, 5);
INSERT INTO JOUEUR
VALUES(508, 14, 'MATUIDI', 'Blaise', 'Francais', 41, 5);

/* Attaquants */
INSERT INTO JOUEUR
VALUES(509, 7, 'GRIEZMANN', 'Antoine', 'Francais', 24, 5);
INSERT INTO JOUEUR
VALUES(510, 8, 'BEN ARFA', 'Hatem', 'Francais', 15, 5);
INSERT INTO JOUEUR
VALUES(511, 11, 'MARTIAL', 'Anthony', 'Francais', 6, 5);

/* ====================================================================================== */

/* Joueurs de l'equipe nationale du Nigeria (6) */

/* Guardien */
INSERT INTO JOUEUR
VALUES(601, 1, 'ENYEAMA', 'Vincent', 'Nigerian', 95, 6);

/* Defenseurs */
INSERT INTO JOUEUR
VALUES(602, 2, 'OBOABONA', 'Godfrey', 'Nigerian', 37, 6);
INSERT INTO JOUEUR
VALUES(603, 4, 'OMERUO', 'Kenneth', 'Nigerian', 22, 6);
INSERT INTO JOUEUR
VALUES(604, 5, 'AMBROSE', 'Efe', 'Nigerian', 42, 6);

/* Milieux */
INSERT INTO JOUEUR
VALUES(605, 8, 'IGIEBOR', 'Nosa', 'Nigerian', 13, 6);
INSERT INTO JOUEUR
VALUES(606, 15, 'AZEEZ', 'Ramon', 'Nigerian', 4, 6);
INSERT INTO JOUEUR
VALUES(607, 17, 'ONAZI', 'Ogenyi', 'Nigerian', 26, 6);
INSERT INTO JOUEUR
VALUES(608, 20, 'OBI', 'Joel', 'Nigerian', 12, 6);

/* Attaquants */
INSERT INTO JOUEUR
VALUES(609, 7, 'MUSA', 'Ahmed', 'Nigerian', 42, 6);
INSERT INTO JOUEUR
VALUES(610, 9, 'EMENIKE', 'Emmanuel', 'Nigerian', 28, 6);
INSERT INTO JOUEUR
VALUES(611, 11, 'ODUAMADI', 'Nnamdi', 'Nigerian', 14, 6);

/* ====================================================================================== */

/* Joueurs de l'equipe nationale d'Allemagne (7) */

/* Guardien */
INSERT INTO JOUEUR
VALUES(701, 1, 'NEUER', 'Manuel', 'Allemand', 58, 7);

/* Defenseurs */
INSERT INTO JOUEUR
VALUES(702, 2, 'MUSTAFI', 'Shkodran', 'Allemand', 8, 7);
INSERT INTO JOUEUR
VALUES(703, 3, 'HECTOR', 'Jonas', 'Allemand', 5, 7);
INSERT INTO JOUEUR
VALUES(704, 4, 'RUDY', 'Sebastian', 'Allemand', 9, 7);

/* Milieux */
INSERT INTO JOUEUR
VALUES(705, 7, 'SCHWEINSTEIGER', 'Bastian', 'Allemand', 111, 7);
INSERT INTO JOUEUR
VALUES(706, 10, 'PODOLOSKI', 'Lukas', 'Allemand', 125, 7);
INSERT INTO JOUEUR
VALUES(707, 16, 'BELLARABI', 'Karim', 'Allemand', 7, 7);
INSERT INTO JOUEUR
VALUES(708, 18, 'KROOS', 'Toni', 'Allemand', 58, 7);
INSERT INTO JOUEUR

/* Attaquants */
INSERT INTO JOUEUR
VALUES(709, 15, 'VOLLAND', 'Kevin', 'Allemand', 3, 7);
INSERT INTO JOUEUR
VALUES(710, 19, 'GOTZE', 'Mario', 'Allemand', 45, 7);
INSERT INTO JOUEUR
VALUES(711, 23, 'KRUSE', 'Max', 'Allemand', 13, 7);

/* ====================================================================================== */

/* Liste des joueurs de l'equipe nationale d'Algerie (8) */

/* Guardien */
INSERT INTO JOUEUR
VALUES(801, 23, 'M BOLHI', 'Rais', 'Algerien', 32, 8);

/* Defenseurs */
INSERT INTO JOUEUR
VALUES(802, 2, 'BOUGHERRA', 'Madjid', 'Algerien', 65, 8);
INSERT INTO JOUEUR
VALUES(803, 12, 'MEDJANI', 'Carl', 'Algerien', 29, 8);
INSERT INTO JOUEUR
VALUES(804, 4, 'BELKALEM', 'Essaid', 'Algerien', 16, 8);

/* Milieux */
INSERT INTO JOUEUR
VALUES(805, 22, 'MOSTEFA', 'Mehdi', 'Algerien', 25, 8);
INSERT INTO JOUEUR
VALUES(806, 7, 'YEBDA', 'Hassan', 'Algerien', 26, 8);
INSERT INTO JOUEUR
VALUES(807, 8, 'LACEN', 'Medhi', 'Algerien', 33, 8);
INSERT INTO JOUEUR
VALUES(808, 19, 'TAIDER', 'Saphir', 'Algerien', 13, 8);

/* Attaquants */
INSERT INTO JOUEUR
VALUES(809, 13, 'SLIMANI', 'Islam', 'Algerien', 24, 8);
INSERT INTO JOUEUR
VALUES(810, 9, 'GHILAS', 'Nabil', 'Algerien', 8, 8);
INSERT INTO JOUEUR
VALUES(811, 15, 'HILLEL SOUDANI', 'El Arbi', 'Algerien', 24, 8);

/* ====================================================================================== */

/* Liste des joueurs de l'equipe nationale des Pays-Bas (9) */

/* Guardien */
INSERT INTO JOUEUR
VALUES(901, 1, 'CILLESSEN', 'Jasper', 'Neerlandais', 4, 9);

/* Defenseurs */
INSERT INTO JOUEUR
VALUES(902, 2, 'VAN DER WIEL', 'Gregory', 'Neerlandais', 36, 9);
INSERT INTO JOUEUR
VALUES(903, 3, 'VELTMAN', 'Joel', 'Neerlandais', 1, 9);
INSERT INTO JOUEUR
VALUES(904, 4, 'VLAAR', 'Ron', 'Neerlandais', 21, 9);

/* Milieux */
INSERT INTO JOUEUR
VALUES(905, 6, 'SCHAARS', 'Stijn', 'Neerlandais', 22, 9);
INSERT INTO JOUEUR
VALUES(906, 8, 'STROOTMAN', 'Kevin', 'Neerlandais', 24, 9);
INSERT INTO JOUEUR
VALUES(907, 10, 'VAN DER VAART', 'Rafael', 'Neerlandais', 109, 9);
INSERT INTO JOUEUR
VALUES(908, 18, 'DE GUZMAN', 'Jonathan', 'Neerlandais', 8, 9);

/* Attaquants */
INSERT INTO JOUEUR
VALUES(909, 7, 'LENS', 'Jeremain', 'Neerlandais', 20, 9);
INSERT INTO JOUEUR
VALUES(910, 11, 'DEPAY', 'Memphis', 'Neerlandais', 3, 9);
INSERT INTO JOUEUR
VALUES(911, 17, 'NARSINGH', 'Lucian', 'Neerlandais', 7, 9);

/* ====================================================================================== */

/* Liste des joueurs de l'equipe nationale du Mexique (10) */

/* Guardien */
INSERT INTO JOUEUR
VALUES(1001, 1, 'CORONA', 'Jose', 'Mexicain', 34, 10);

/* Defenseurs */
INSERT INTO JOUEUR
VALUES(1002, 2, 'JAVIER RODRIGUEZ', 'Francisco', 'Mexicain', 95, 10);
INSERT INTO JOUEUR
VALUES(1003, 3, 'SALCIDO', 'Carlos', 'Mexicain', 122, 10);
INSERT INTO JOUEUR
VALUES(1004, 4, 'MARQUEZ', 'Rafael', 'Mexicain', 120, 10);

/* Milieux */
INSERT INTO JOUEUR
VALUES(1005, 6, 'HERRERA', 'Hector', 'Mexicain', 13, 10);
INSERT INTO JOUEUR
VALUES(1006, 8, 'FABIAN', 'Marco', 'Mexicain', 15, 10);
INSERT INTO JOUEUR
VALUES(1007, 17, 'BRIZUELA', 'Isaac', 'Mexicain', 7, 10);
INSERT INTO JOUEUR
VALUES(1008, 20, 'AQUINO', 'Javier', 'Mexicain', 22, 10);

/* Attaquants */
INSERT INTO JOUEUR
VALUES(1009, 9, 'JIMENEZ', 'Raul', 'Mexicain', 25, 10);
INSERT INTO JOUEUR
VALUES(1010, 10, 'DOS SANTOS', 'Giovani', 'Mexicain', 76, 10);
INSERT INTO JOUEUR
VALUES(1011, 11, 'PULIDO', 'Alan', 'Mexicain', 6, 10);

/* ====================================================================================== */

/* Liste des joueurs de l'equipe nationale du Costa Rica (11) */

/* Guardien */
INSERT INTO JOUEUR
VALUES(1101, 1, 'NAVAS', 'KEYLOR', 'Costaricien', 61, 11);

/* Defenseurs */
INSERT INTO JOUEUR
VALUES(1102, 2, 'DUARTE', 'Oscar', 'Costaricien', 21, 11);
INSERT INTO JOUEUR
VALUES(1103, 3, 'MYRIE', 'Dave', 'Costaricien', 18, 11);
INSERT INTO JOUEUR
VALUES(1104, 4, 'CALVO', 'Francisco', 'Costaricien', 4, 11);

/* Milieux */
INSERT INTO JOUEUR
VALUES(1105, 5, 'BORGES', 'Celso', 'Costaricien', 75, 11);
INSERT INTO JOUEUR
VALUES(1106, 7, 'GUZMAN', 'David', 'Costaricien', 10, 11);
INSERT INTO JOUEUR
VALUES(1107, 14, 'BOLANOS', 'Christian', 'Costaricien', 60, 11);
INSERT INTO JOUEUR
VALUES(1108, 10, 'VENEGAS', 'Johan', 'Costaricien', 8, 11);

/* Attaquants */
INSERT INTO JOUEUR
VALUES(1109, 10, 'RUIZ', 'Bryan', 'Costaricien', 74, 11);
INSERT INTO JOUEUR
VALUES(1110, 9, 'SABORIO', 'Alvaro', 'Costaricien', 98, 11);
INSERT INTO JOUEUR
VALUES(1111, 12, 'CAMPBELL', 'Joel', 'Costaricien', 44, 11);

/* ====================================================================================== */

/* Liste des joueurs de l'equipe nationale de Grece (12) */

/* Guardien */
INSERT INTO JOUEUR
VALUES(1201, 1, 'KARNEZIS', 'Orestis', 'Grec', 28, 12);

/* Defenseurs */
INSERT INTO JOUEUR
VALUES(1202, 3, 'FYTANIDIS', 'Sokratis', 'Grec', 0, 12);
INSERT INTO JOUEUR
VALUES(1203, 5, 'HOLEBAS', 'Jose', 'Grec', 13, 12);
INSERT INTO JOUEUR
VALUES(1204, 7, 'MANOLAS', 'Kostas', 'Grec', 2, 12);

/* Milieux */
INSERT INTO JOUEUR
VALUES(1205, 9, 'DIMOUTSOS', 'Elini', 'Grec', 1, 12);
INSERT INTO JOUEUR
VALUES(1206, 11, 'FETFATZIDIS', 'Ioannis', 'Grec', 13, 12);
INSERT INTO JOUEUR
VALUES(1207, 13, 'FORTOUNIS', 'Konstantinos', 'Grec', 11, 12);
INSERT INTO JOUEUR
VALUES(1208, 15, 'KATSOURANIS', 'Kostas', 'Grec', 103, 12);

/* Attaquants */
INSERT INTO JOUEUR
VALUES(1209, 17, 'ATHANASIADIS', 'Stefanos', 'Grec', 4, 12);
INSERT INTO JOUEUR
VALUES(1210, 19, 'CHRISTODOULOPOULOS', 'Lazaros', 'Grec', 10, 12);
INSERT INTO JOUEUR
VALUES(1211, 21, 'MITROGLOU', 'Konstantinos', 'Grec', 38, 12);

/* ====================================================================================== */

/* Liste des joueurs de l'equipe nationale d'Argentine (13) */

/* Guardien */
INSERT INTO JOUEUR
VALUES(1301, 1, 'ROMERO', 'Sergio', 'Argentin', 66, 13);

/* Defenseurs */
INSERT INTO JOUEUR
VALUES(1302, 4, 'ZABALETA', 'Pablo', 'Argentin', 53, 13);
INSERT INTO JOUEUR
VALUES(1303, 16, 'ROJO', 'Marcos', 'Argentin', 40, 13);
INSERT INTO JOUEUR
VALUES(1304, 3, 'OTAMENDI', 'Nicolas', 'Argentin', 26, 13);

/* Milieux */
INSERT INTO JOUEUR
VALUES(1305, 14, 'MASCHERANO', 'Javier', 'Argentin', 118, 13);
INSERT INTO JOUEUR
VALUES(1306, 7, 'DI MARIA', 'Angel', 'Argentin', 66, 13);
INSERT INTO JOUEUR
VALUES(1307, 15, 'BIGLIA', 'Lucas', 'Argentin', 35, 13);
INSERT INTO JOUEUR
VALUES(1308, 19, 'BANEGA', 'Ever', 'Argentin', 36, 13);

/* Attaquants */
INSERT INTO JOUEUR
VALUES(1309, 10, 'MESSI', 'Lionel', 'Argentin', 105, 13);
INSERT INTO JOUEUR
VALUES(1310, 23, 'TEVEZ', 'Carlos', 'Argentin', 74, 13);
INSERT INTO JOUEUR
VALUES(1311, 11, 'AGUERO', 'Sergio', 'Argentin', 68, 13);

/* ====================================================================================== */

/* Liste des joueurs de l'equipe nationale de Suisse (14) */

/* Guardien */
INSERT INTO JOUEUR
VALUES(1401, 1, 'SOMMER', 'Yann', 'Suisse', 15, 14);

/* Defenseurs */
INSERT INTO JOUEUR
VALUES(1402, 3, 'LICHSTEINER', 'Stephan', 'Suisse', 79, 14);
INSERT INTO JOUEUR
VALUES(1403, 5, 'MOUBANDJE', 'Francois', 'Suisse', 8, 14);
INSERT INTO JOUEUR
VALUES(1404, 7, 'KLOSE', 'Timm', 'Suisse', 12, 14);

/* Milieux */
INSERT INTO JOUEUR
VALUES(1405, 9, 'INLER', 'Gokhan', 'Suisse', 89, 14);
INSERT INTO JOUEUR
VALUES(1406, 11, 'ZUFFI', 'Luca', 'Suisse', 3, 14);
INSERT INTO JOUEUR
VALUES(1407, 13, 'BEHRAMI', 'Valon', 'Suisse', 63, 14);
INSERT INTO JOUEUR
VALUES(1408, 15, 'STOCKER', 'Valentin', 'Suisse', 33, 14);

/* Attaquants */
INSERT INTO JOUEUR
VALUES(1409, 17, 'SEFEROVIC', 'Haris', 'Suisse', 27, 14);
INSERT INTO JOUEUR
VALUES(1410, 19, 'DERDIYOK', 'Eren', 'Suisse', 50, 14);
INSERT INTO JOUEUR
VALUES(1411, 21, 'MEHMEDI', 'Admir', 'Suisse', 38, 14);

/* ====================================================================================== */

/* Liste des joueurs de l'equipe nationale de Belgique (15) */

/* Guardien */
INSERT INTO JOUEUR
VALUES(1501, 1, 'COURTOIS', 'Thibaut', 'Belge', 17, 15);

/* Defenseurs */
INSERT INTO JOUEUR
VALUES(1502, 2, 'ALDERWEIRELD', 'Toby', 'Belge', 34, 15);
INSERT INTO JOUEUR
VALUES(1503, 3, 'VERMAELEN', 'Thomas', 'Belge', 47, 15);
INSERT INTO JOUEUR
VALUES(1504, 4, 'KOMPANY', 'Vincent', 'Belge', 59, 15);

/* Milieux */
INSERT INTO JOUEUR
VALUES(1505, 6, 'WITSEL', 'Axel', 'Belge', 48, 15);
INSERT INTO JOUEUR
VALUES(1506, 7, 'DE BRUYNE', 'Kevin', 'Belge', 21, 15);
INSERT INTO JOUEUR
VALUES(1507, 8, 'FELLAINI', 'Marouane', 'Belge', 50, 15);
INSERT INTO JOUEUR
VALUES(1508, 16, 'DEFOUR', 'Steven', 'Belge', 43, 15);

/* Attaquants */
INSERT INTO JOUEUR
VALUES(1509, 9, 'LUKAKU', 'Romelu', 'Belge', 29, 15);
INSERT INTO JOUEUR
VALUES(1510, 10, 'HAZARD', 'Eden', 'Belge', 45, 15);
INSERT INTO JOUEUR
VALUES(1511, 11, 'MIRALLAS', 'Kevin', 'Belge', 44, 15);

/* ====================================================================================== */

/* Liste des joueurs de l'equipe nationale des Etats-Unis (16) */

/* Guardien */
INSERT INTO JOUEUR
VALUES(1601, 1, 'HOWARD', 'Tim', 'Americain', 104, 16);

/* Defenseurs */
INSERT INTO JOUEUR
VALUES(1602, 2, 'YEDLIN', 'DeAndre', 'Americain', 7, 16);
INSERT INTO JOUEUR
VALUES(1603, 3, 'GONZALES', 'Omar', 'Americain', 23, 16);
INSERT INTO JOUEUR
VALUES(1604, 5, 'BESLER', 'Matt', 'Americain', 21, 16);

/* Milieux */
INSERT INTO JOUEUR
VALUES(1605, 4, 'BARDLEY', 'Michael', 'Americain', 90, 16);
INSERT INTO JOUEUR
VALUES(1606, 10, 'DISKERUD', 'Mikkel', 'Americain', 20, 16);
INSERT INTO JOUEUR
VALUES(1607, 11, 'BEDOYA', 'Alejandro', 'Americain', 32, 16);
INSERT INTO JOUEUR
VALUES(1608, 13, 'JONES', 'Jermaine', 'Americain', 46, 16);

/* Attaquants */
INSERT INTO JOUEUR
VALUES(1609, 8, 'DEMPSEY', 'Clint', 'Americain', 109, 16);
INSERT INTO JOUEUR
VALUES(1610, 9, 'JOHANNSSON', 'Aron', 'Americain', 9, 16);
INSERT INTO JOUEUR
VALUES(1611, 17, 'ALTIDORE', 'Jozy', 'Americain', 71, 16);

/* ====================================================================================== */


/* ====================================================================================== */
/* 				       LISTE DES EQUIPES                                  */
/* ====================================================================================== */

INSERT INTO EQUIPE
VALUES(1, 'Bresil', 80000, 192000000);
INSERT INTO EQUIPE
VALUES(2, 'Chili', 63649, 162000000);
INSERT INTO EQUIPE
VALUES(3, 'Colombie', 60000, 147000000);
INSERT INTO EQUIPE
VALUES(4, 'Uruguay', 65000, 178000000);
INSERT INTO EQUIPE
VALUES(5, 'France', 81338, 205000000);
INSERT INTO EQUIPE
VALUES(6, 'Nigeria', 60000, 153000000);
INSERT INTO EQUIPE
VALUES(7, 'Allemagne', 80645, 165000000);
INSERT INTO EQUIPE
VALUES(8, 'Algerie', 85000, 67000000);
INSERT INTO EQUIPE
VALUES(9, 'Pays-Bas', 53502, 145000000);
INSERT INTO EQUIPE
VALUES(10, 'Mexique', 105064, 193000000);
INSERT INTO EQUIPE
VALUES(11, 'Costa Rica', 35100, 134000000);
INSERT INTO EQUIPE
VALUES(12, 'Grece', 71030, 420000);
INSERT INTO EQUIPE
VALUES(13, 'Argentine', 65645, 187000000);
INSERT INTO EQUIPE
VALUES(14, 'Suisse', 31783, 142000000);
INSERT INTO EQUIPE
VALUES(15, 'Belgique', 50000, 154000000);
INSERT INTO EQUIPE
VALUES(16, 'Etats-Unis', 109801, 212000000);

/* ====================================================================================== */


/* ====================================================================================== */
/*                                  LISTE DES COMPETITIONS                                */
/* ====================================================================================== */

/* Liste des Coupes du Monde */
INSERT INTO COMPETITION
VALUES(1, 'Coupe du Monde', 'Coupe', 2014, 7);
INSERT INTO COMPETITION
VALUES(2, 'Coupe du Monde', 'Coupe', 2010, 15);
INSERT INTO COMPETITION
VALUES(3, 'Coupe du Monde', 'Coupe', 1998, 3);

/* Liste des Coupes de France */
INSERT INTO COMPETITION
VALUES(4, 'Coupe de France', 'Coupe', 2012, 10);
INSERT INTO COMPETITION
VALUES(5, 'Coupe de France', 'Coupe', 2008, 15);
INSERT INTO COMPETITION
VALUES(6, 'Coupe de France', 'Coupe', 2004, 4);

/* Liste des Ligues des Champions */
INSERT INTO COMPETITION
VALUES(7, 'Ligue des Champions', 'Ligue', 2015, 12);
INSERT INTO COMPETITION
VALUES(8, 'Ligue des Champions', 'Ligue', 2013, 10);
INSERT INTO COMPETITION
VALUES(9, 'Ligue des Champions', 'Ligue', 2011, 8);

/* Liste des Championnats */
INSERT INTO COMPETITION
VALUES(10, 'Championnat', 'Championnat', 2010, 1);
INSERT INTO COMPETITION
VALUES(11, 'Championnat', 'Championnat', 2006, 3);
INSERT INTO COMPETITION
VALUES(12, 'Championnat', 'Championnat', 2002, 6);


/* ====================================================================================== */

/* ====================================================================================== */
/*									 LISTE DES PALMARESJ							      */
/* ====================================================================================== */


INSERT INTO PALMARESJ
VALUES(101, 10);
INSERT INTO PALMARESJ
VALUES(102, 10);
INSERT INTO PALMARESJ
VALUES(103, 10);
INSERT INTO PALMARESJ
VALUES(104, 10);
INSERT INTO PALMARESJ
VALUES(105, 10);
INSERT INTO PALMARESJ
VALUES(106, 10);
INSERT INTO PALMARESJ
VALUES(107, 10);
INSERT INTO PALMARESJ
VALUES(108, 10);
INSERT INTO PALMARESJ
VALUES(109, 10);
INSERT INTO PALMARESJ
VALUES(110, 10);
INSERT INTO PALMARESJ
VALUES(111, 10);

INSERT INTO PALMARESJ
VALUES(301, 3);
INSERT INTO PALMARESJ
VALUES(302, 3);
INSERT INTO PALMARESJ
VALUES(303, 3);
INSERT INTO PALMARESJ
VALUES(304, 3);
INSERT INTO PALMARESJ
VALUES(305, 3);
INSERT INTO PALMARESJ
VALUES(306, 3);
INSERT INTO PALMARESJ
VALUES(307, 3);
INSERT INTO PALMARESJ
VALUES(308, 3);
INSERT INTO PALMARESJ
VALUES(309, 3);
INSERT INTO PALMARESJ
VALUES(310, 3);
INSERT INTO PALMARESJ
VALUES(311, 3);
INSERT INTO PALMARESJ
VALUES(301, 11);
INSERT INTO PALMARESJ
VALUES(302, 11);
INSERT INTO PALMARESJ
VALUES(303, 11);
INSERT INTO PALMARESJ
VALUES(304, 11);
INSERT INTO PALMARESJ
VALUES(305, 11);
INSERT INTO PALMARESJ
VALUES(306, 11);
INSERT INTO PALMARESJ
VALUES(307, 11);
INSERT INTO PALMARESJ
VALUES(308, 11);
INSERT INTO PALMARESJ
VALUES(309, 11);
INSERT INTO PALMARESJ
VALUES(310, 11);
INSERT INTO PALMARESJ
VALUES(311, 11);

INSERT INTO PALMARESJ
VALUES(401, 6);
INSERT INTO PALMARESJ
VALUES(402, 6);
INSERT INTO PALMARESJ
VALUES(403, 6);
INSERT INTO PALMARESJ
VALUES(404, 6);
INSERT INTO PALMARESJ
VALUES(405, 6);
INSERT INTO PALMARESJ
VALUES(406, 6);
INSERT INTO PALMARESJ
VALUES(407, 6);
INSERT INTO PALMARESJ
VALUES(408, 6);
INSERT INTO PALMARESJ
VALUES(409, 6);
INSERT INTO PALMARESJ
VALUES(410, 6);
INSERT INTO PALMARESJ
VALUES(411, 6);

INSERT INTO PALMARESJ
VALUES(601, 12);
INSERT INTO PALMARESJ
VALUES(602, 12);
INSERT INTO PALMARESJ
VALUES(603, 12);
INSERT INTO PALMARESJ
VALUES(604, 12);
INSERT INTO PALMARESJ
VALUES(605, 12);
INSERT INTO PALMARESJ
VALUES(606, 12);
INSERT INTO PALMARESJ
VALUES(607, 12);
INSERT INTO PALMARESJ
VALUES(608, 12);
INSERT INTO PALMARESJ
VALUES(609, 12);
INSERT INTO PALMARESJ
VALUES(610, 12);
INSERT INTO PALMARESJ
VALUES(611, 12);

INSERT INTO PALMARESJ
VALUES(701, 1);
INSERT INTO PALMARESJ
VALUES(702, 1);
INSERT INTO PALMARESJ
VALUES(703, 1);
INSERT INTO PALMARESJ
VALUES(704, 1);
INSERT INTO PALMARESJ
VALUES(705, 1);
INSERT INTO PALMARESJ
VALUES(706, 1);
INSERT INTO PALMARESJ
VALUES(707, 1);
INSERT INTO PALMARESJ
VALUES(708, 1);
INSERT INTO PALMARESJ
VALUES(709, 1);
INSERT INTO PALMARESJ
VALUES(710, 1);
INSERT INTO PALMARESJ
VALUES(711, 1);

INSERT INTO PALMARESJ
VALUES(801, 9);
INSERT INTO PALMARESJ
VALUES(802, 9);
INSERT INTO PALMARESJ
VALUES(803, 9);
INSERT INTO PALMARESJ
VALUES(804, 9);
INSERT INTO PALMARESJ
VALUES(805, 9);
INSERT INTO PALMARESJ
VALUES(806, 9);
INSERT INTO PALMARESJ
VALUES(807, 9);
INSERT INTO PALMARESJ
VALUES(808, 9);
INSERT INTO PALMARESJ
VALUES(809, 9);
INSERT INTO PALMARESJ
VALUES(810, 9);
INSERT INTO PALMARESJ
VALUES(811, 9);

INSERT INTO PALMARESJ
VALUES(1001, 4);
INSERT INTO PALMARESJ
VALUES(1002, 4);
INSERT INTO PALMARESJ
VALUES(1003, 4);
INSERT INTO PALMARESJ
VALUES(1004, 4);
INSERT INTO PALMARESJ
VALUES(1005, 4);
INSERT INTO PALMARESJ
VALUES(1006, 4);
INSERT INTO PALMARESJ
VALUES(1007, 4);
INSERT INTO PALMARESJ
VALUES(1008, 4);
INSERT INTO PALMARESJ
VALUES(1009, 4);
INSERT INTO PALMARESJ
VALUES(1010, 4);
INSERT INTO PALMARESJ
VALUES(1011, 4);

INSERT INTO PALMARESJ
VALUES(1001, 8);
INSERT INTO PALMARESJ
VALUES(1002, 8);
INSERT INTO PALMARESJ
VALUES(1003, 8);
INSERT INTO PALMARESJ
VALUES(1004, 8);
INSERT INTO PALMARESJ
VALUES(1005, 8);
INSERT INTO PALMARESJ
VALUES(1006, 8);
INSERT INTO PALMARESJ
VALUES(1007, 8);
INSERT INTO PALMARESJ
VALUES(1008, 8);
INSERT INTO PALMARESJ
VALUES(1009, 8);
INSERT INTO PALMARESJ
VALUES(1010, 8);
INSERT INTO PALMARESJ
VALUES(1011, 8);

INSERT INTO PALMARESJ
VALUES(1201, 7);
INSERT INTO PALMARESJ
VALUES(1202, 7);
INSERT INTO PALMARESJ
VALUES(1203, 7);
INSERT INTO PALMARESJ
VALUES(1204, 7);
INSERT INTO PALMARESJ
VALUES(1205, 7);
INSERT INTO PALMARESJ
VALUES(1206, 7);
INSERT INTO PALMARESJ
VALUES(1207, 7);
INSERT INTO PALMARESJ
VALUES(1208, 7);
INSERT INTO PALMARESJ
VALUES(1209, 7);
INSERT INTO PALMARESJ
VALUES(1210, 7);
INSERT INTO PALMARESJ
VALUES(1211, 7);

INSERT INTO PALMARESJ
VALUES(1501, 2);
INSERT INTO PALMARESJ
VALUES(1502, 2);
INSERT INTO PALMARESJ
VALUES(1503, 2);
INSERT INTO PALMARESJ
VALUES(1504, 2);
INSERT INTO PALMARESJ
VALUES(1505, 2);
INSERT INTO PALMARESJ
VALUES(1506, 2);
INSERT INTO PALMARESJ
VALUES(1507, 2);
INSERT INTO PALMARESJ
VALUES(1508, 2);
INSERT INTO PALMARESJ
VALUES(1509, 2);
INSERT INTO PALMARESJ
VALUES(1510, 2);
INSERT INTO PALMARESJ
VALUES(1511, 2);

INSERT INTO PALMARESJ
VALUES(1501, 5);
INSERT INTO PALMARESJ
VALUES(1502, 5);
INSERT INTO PALMARESJ
VALUES(1503, 5);
INSERT INTO PALMARESJ
VALUES(1504, 5);
INSERT INTO PALMARESJ
VALUES(1505, 5);
INSERT INTO PALMARESJ
VALUES(1506, 5);
INSERT INTO PALMARESJ
VALUES(1507, 5);
INSERT INTO PALMARESJ
VALUES(1508, 5);
INSERT INTO PALMARESJ
VALUES(1509, 5);
INSERT INTO PALMARESJ
VALUES(1510, 5);
INSERT INTO PALMARESJ
VALUES(1511, 5);


/* ====================================================================================== */

/* ====================================================================================== */
/*                                  LISTE DES PARTICIPATIONS                              */
/* ====================================================================================== */


/* Participations pour les Coupes du Monde */

/* Coupe du Monde de 2014 */
INSERT INTO PARTICIPER
VALUES(1, 1, 7);
INSERT INTO PARTICIPER
VALUES(2, 1, 13);
INSERT INTO PARTICIPER
VALUES(3, 1, 9);
INSERT INTO PARTICIPER
VALUES(4, 1, 1);
INSERT INTO PARTICIPER
VALUES(5, 1, 3);
INSERT INTO PARTICIPER
VALUES(5, 1, 5);
INSERT INTO PARTICIPER
VALUES(5, 1, 11);
INSERT INTO PARTICIPER
VALUES(5, 1, 15);
INSERT INTO PARTICIPER
VALUES(6, 1, 2);
INSERT INTO PARTICIPER
VALUES(6, 1, 4);
INSERT INTO PARTICIPER
VALUES(6, 1, 6);
INSERT INTO PARTICIPER
VALUES(6, 1, 8);
INSERT INTO PARTICIPER
VALUES(6, 1, 10);
INSERT INTO PARTICIPER
VALUES(6, 1, 12);
INSERT INTO PARTICIPER
VALUES(6, 1, 14);
INSERT INTO PARTICIPER
VALUES(6, 1, 16);

/* Coupe du Monde de 2010 */
INSERT INTO PARTICIPER
VALUES(1, 2, 15);
INSERT INTO PARTICIPER
VALUES(2, 2, 5);
INSERT INTO PARTICIPER
VALUES(3, 2, 11);
INSERT INTO PARTICIPER
VALUES(4, 2, 1);
INSERT INTO PARTICIPER
VALUES(5, 2, 4);
INSERT INTO PARTICIPER
VALUES(5, 2, 7);
INSERT INTO PARTICIPER
VALUES(5, 2, 9);
INSERT INTO PARTICIPER
VALUES(5, 2, 13);
INSERT INTO PARTICIPER
VALUES(6, 2, 2);
INSERT INTO PARTICIPER
VALUES(6, 2, 3);
INSERT INTO PARTICIPER
VALUES(6, 2, 6);
INSERT INTO PARTICIPER
VALUES(6, 2, 8);
INSERT INTO PARTICIPER
VALUES(6, 2, 10);
INSERT INTO PARTICIPER
VALUES(6, 2, 12);
INSERT INTO PARTICIPER
VALUES(6, 2, 14);
INSERT INTO PARTICIPER
VALUES(6, 2, 16);

/* Coupe du Monde de 1998 */
INSERT INTO PARTICIPER
VALUES(1, 3, 3);
INSERT INTO PARTICIPER
VALUES(2, 3, 9);
INSERT INTO PARTICIPER
VALUES(3, 3, 8);
INSERT INTO PARTICIPER
VALUES(4, 3, 13);
INSERT INTO PARTICIPER
VALUES(5, 3, 1);
INSERT INTO PARTICIPER
VALUES(5, 3, 5);
INSERT INTO PARTICIPER
VALUES(5, 3, 12);
INSERT INTO PARTICIPER
VALUES(5, 3, 15);
INSERT INTO PARTICIPER
VALUES(6, 3, 2);
INSERT INTO PARTICIPER
VALUES(6, 3, 4);
INSERT INTO PARTICIPER
VALUES(6, 3, 6);
INSERT INTO PARTICIPER
VALUES(6, 3, 7);
INSERT INTO PARTICIPER
VALUES(6, 3, 10);
INSERT INTO PARTICIPER
VALUES(6, 3, 11);
INSERT INTO PARTICIPER
VALUES(6, 3, 14);
INSERT INTO PARTICIPER
VALUES(6, 3, 16);


/* Participations pour les Coupes de France */

/* Coupe de France de 2012 */
INSERT INTO PARTICIPER
VALUES(1, 4, 10);
INSERT INTO PARTICIPER
VALUES(2, 4, 2);
INSERT INTO PARTICIPER
VALUES(3, 4, 3);
INSERT INTO PARTICIPER
VALUES(4, 4, 4);
INSERT INTO PARTICIPER
VALUES(5, 4, 5);
INSERT INTO PARTICIPER
VALUES(5, 4, 6);
INSERT INTO PARTICIPER
VALUES(5, 4, 7);
INSERT INTO PARTICIPER
VALUES(5, 4, 8);
INSERT INTO PARTICIPER
VALUES(6, 4, 9);
INSERT INTO PARTICIPER
VALUES(6, 4, 1);
INSERT INTO PARTICIPER
VALUES(6, 4, 11);
INSERT INTO PARTICIPER
VALUES(6, 4, 12);
INSERT INTO PARTICIPER
VALUES(6, 4, 13);
INSERT INTO PARTICIPER
VALUES(6, 4, 14);
INSERT INTO PARTICIPER
VALUES(6, 4, 15);
INSERT INTO PARTICIPER
VALUES(6, 4, 16);

/* Coupe de France de 2008 */
INSERT INTO PARTICIPER
VALUES(1, 5, 15);
INSERT INTO PARTICIPER
VALUES(2, 5, 16);
INSERT INTO PARTICIPER
VALUES(3, 5, 14);
INSERT INTO PARTICIPER
VALUES(4, 5, 13);
INSERT INTO PARTICIPER
VALUES(5, 5, 12);
INSERT INTO PARTICIPER
VALUES(5, 5, 11);
INSERT INTO PARTICIPER
VALUES(5, 5, 10);
INSERT INTO PARTICIPER
VALUES(5, 5, 9);
INSERT INTO PARTICIPER
VALUES(6, 5, 8);
INSERT INTO PARTICIPER
VALUES(6, 5, 7);
INSERT INTO PARTICIPER
VALUES(6, 5, 6);
INSERT INTO PARTICIPER
VALUES(6, 5, 5);
INSERT INTO PARTICIPER
VALUES(6, 5, 4);
INSERT INTO PARTICIPER
VALUES(6, 5, 3);
INSERT INTO PARTICIPER
VALUES(6, 5, 2);
INSERT INTO PARTICIPER
VALUES(6, 5, 1);

/* Coupe de France de 2004 */
INSERT INTO PARTICIPER
VALUES(1, 6, 4);
INSERT INTO PARTICIPER
VALUES(2, 6, 8);
INSERT INTO PARTICIPER
VALUES(3, 6, 12);
INSERT INTO PARTICIPER
VALUES(4, 6, 16);
INSERT INTO PARTICIPER
VALUES(5, 6, 2);
INSERT INTO PARTICIPER
VALUES(5, 6, 6);
INSERT INTO PARTICIPER
VALUES(5, 6, 10);
INSERT INTO PARTICIPER
VALUES(5, 6, 14);
INSERT INTO PARTICIPER
VALUES(6, 6, 3);
INSERT INTO PARTICIPER
VALUES(6, 6, 7);
INSERT INTO PARTICIPER
VALUES(6, 6, 11);
INSERT INTO PARTICIPER
VALUES(6, 6, 15);
INSERT INTO PARTICIPER
VALUES(6, 6, 1);
INSERT INTO PARTICIPER
VALUES(6, 6, 5);
INSERT INTO PARTICIPER
VALUES(6, 6, 9);
INSERT INTO PARTICIPER
VALUES(6, 6, 13);


/* Participations pour les Ligues des Champions */

/* Ligues des Champions de 2015 */
INSERT INTO PARTICIPER
VALUES(1, 7, 12);
INSERT INTO PARTICIPER
VALUES(2, 7, 1);
INSERT INTO PARTICIPER
VALUES(3, 7, 3);
INSERT INTO PARTICIPER
VALUES(4, 7, 6);
INSERT INTO PARTICIPER
VALUES(5, 7, 9);
INSERT INTO PARTICIPER
VALUES(5, 7, 2);
INSERT INTO PARTICIPER
VALUES(5, 7, 7);
INSERT INTO PARTICIPER
VALUES(5, 7, 8);
INSERT INTO PARTICIPER
VALUES(6, 7, 14);
INSERT INTO PARTICIPER
VALUES(6, 7, 16);
INSERT INTO PARTICIPER
VALUES(6, 7, 4);
INSERT INTO PARTICIPER
VALUES(6, 7, 15);
INSERT INTO PARTICIPER
VALUES(6, 7, 10);
INSERT INTO PARTICIPER
VALUES(6, 7, 5);
INSERT INTO PARTICIPER
VALUES(6, 7, 11);
INSERT INTO PARTICIPER
VALUES(6, 7, 13);

/* Ligues des Champions de 2013 */
INSERT INTO PARTICIPER
VALUES(1, 8, 10);
INSERT INTO PARTICIPER
VALUES(2, 8, 12);
INSERT INTO PARTICIPER
VALUES(3, 8, 14);
INSERT INTO PARTICIPER
VALUES(4, 8, 16);
INSERT INTO PARTICIPER
VALUES(5, 8, 8);
INSERT INTO PARTICIPER
VALUES(5, 8, 6);
INSERT INTO PARTICIPER
VALUES(5, 8, 4);
INSERT INTO PARTICIPER
VALUES(5, 8, 2);
INSERT INTO PARTICIPER
VALUES(6, 8, 11);
INSERT INTO PARTICIPER
VALUES(6, 8, 13);
INSERT INTO PARTICIPER
VALUES(6, 8, 15);
INSERT INTO PARTICIPER
VALUES(6, 8, 9);
INSERT INTO PARTICIPER
VALUES(6, 8, 7);
INSERT INTO PARTICIPER
VALUES(6, 8, 5);
INSERT INTO PARTICIPER
VALUES(6, 8, 3);
INSERT INTO PARTICIPER
VALUES(6, 8, 1);

/* Ligues des Champions de 2011 */
INSERT INTO PARTICIPER
VALUES(1, 9, 8);
INSERT INTO PARTICIPER
VALUES(2, 9, 10);
INSERT INTO PARTICIPER
VALUES(3, 9, 6);
INSERT INTO PARTICIPER
VALUES(4, 9, 12);
INSERT INTO PARTICIPER
VALUES(5, 9, 4);
INSERT INTO PARTICIPER
VALUES(5, 9, 14);
INSERT INTO PARTICIPER
VALUES(5, 9, 2);
INSERT INTO PARTICIPER
VALUES(5, 9, 16);
INSERT INTO PARTICIPER
VALUES(6, 9, 1);
INSERT INTO PARTICIPER
VALUES(6, 9, 15);
INSERT INTO PARTICIPER
VALUES(6, 9, 3);
INSERT INTO PARTICIPER
VALUES(6, 9, 13);
INSERT INTO PARTICIPER
VALUES(6, 9, 5);
INSERT INTO PARTICIPER
VALUES(6, 9, 11);
INSERT INTO PARTICIPER
VALUES(6, 9, 7);
INSERT INTO PARTICIPER
VALUES(6, 9, 9);


/* Liste des Championnats */

/* Championnat de 2010 */
INSERT INTO PARTICIPER
VALUES(1, 10, 1);
INSERT INTO PARTICIPER
VALUES(2, 10, 3);
INSERT INTO PARTICIPER
VALUES(3, 10, 5);
INSERT INTO PARTICIPER
VALUES(4, 10, 9);
INSERT INTO PARTICIPER
VALUES(5, 10, 11);
INSERT INTO PARTICIPER
VALUES(5, 10, 13);
INSERT INTO PARTICIPER
VALUES(5, 10, 15);
INSERT INTO PARTICIPER
VALUES(5, 10, 2);
INSERT INTO PARTICIPER
VALUES(6, 10, 4);
INSERT INTO PARTICIPER
VALUES(6, 10, 6);
INSERT INTO PARTICIPER
VALUES(6, 10, 8);
INSERT INTO PARTICIPER
VALUES(6, 10, 10);
INSERT INTO PARTICIPER
VALUES(6, 10, 12);
INSERT INTO PARTICIPER
VALUES(6, 10, 14);
INSERT INTO PARTICIPER
VALUES(6, 10, 16);
INSERT INTO PARTICIPER
VALUES(6, 10, 7);

/* Championnat de 2006 */
INSERT INTO PARTICIPER
VALUES(1, 11, 3);
INSERT INTO PARTICIPER
VALUES(2, 11, 4);
INSERT INTO PARTICIPER
VALUES(3, 11, 5);
INSERT INTO PARTICIPER
VALUES(4, 11, 6);
INSERT INTO PARTICIPER
VALUES(5, 11, 1);
INSERT INTO PARTICIPER
VALUES(5, 11, 9);
INSERT INTO PARTICIPER
VALUES(5, 11, 8);
INSERT INTO PARTICIPER
VALUES(5, 11, 7);
INSERT INTO PARTICIPER
VALUES(6, 11, 2);
INSERT INTO PARTICIPER
VALUES(6, 11, 10);
INSERT INTO PARTICIPER
VALUES(6, 11, 12);
INSERT INTO PARTICIPER
VALUES(6, 11, 14);
INSERT INTO PARTICIPER
VALUES(6, 11, 16);
INSERT INTO PARTICIPER
VALUES(6, 11, 11);
INSERT INTO PARTICIPER
VALUES(6, 11, 13);
INSERT INTO PARTICIPER
VALUES(6, 11, 15);

/* Championnat de 2002 */
INSERT INTO PARTICIPER
VALUES(1, 12, 6);
INSERT INTO PARTICIPER
VALUES(2, 12, 4);
INSERT INTO PARTICIPER
VALUES(3, 12, 2);
INSERT INTO PARTICIPER
VALUES(4, 12, 8);
INSERT INTO PARTICIPER
VALUES(5, 12, 10);
INSERT INTO PARTICIPER
VALUES(5, 12, 12);
INSERT INTO PARTICIPER
VALUES(5, 12, 16);
INSERT INTO PARTICIPER
VALUES(5, 12, 14);
INSERT INTO PARTICIPER
VALUES(6, 12, 1);
INSERT INTO PARTICIPER
VALUES(6, 12, 3);
INSERT INTO PARTICIPER
VALUES(6, 12, 7);
INSERT INTO PARTICIPER
VALUES(6, 12, 5);
INSERT INTO PARTICIPER
VALUES(6, 12, 9);
INSERT INTO PARTICIPER
VALUES(6, 12, 11);
INSERT INTO PARTICIPER
VALUES(6, 12, 13);
INSERT INTO PARTICIPER
VALUES(6, 12, 15);
